application: usersource-anno
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

#inbound_services:
#- warmup

handlers:
- url: /_ah/spi/.*
  script: services.APPLICATION
- url: /update_schema
  script: main.application
  login: admin
- url: /push
  script: main.application
  login: admin
- url: /appinfo
  script: main.application
  login: admin
- url: /docs
  static_dir: docs/build/html
  login: admin
- url: /dashboard/login/(.*\.(bmp|gif|ico|jpeg|jpg|png|js|css))
  static_files: dashboard/\1
  upload: dashboard/(.*\.(bmp|gif|ico|jpeg|jpg|png|js|css))
- url: /dashboard/login(/.*)*
  static_files: dashboard/login.html
  upload: dashboard/(.*)
- url: /dashboard/feed
  static_files: dashboard/feed.html
  upload: dashboard/(.*)
- url: /dashboard
  static_dir: dashboard
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
- name: ssl
  version: latest
