application: usersource-anno
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: services.APPLICATION
- url: /update_schema
  script: main.application
  login: admin
- url: /docs
  static_dir: docs/build/html
  login: admin
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
