application: usersource-anno
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: services.APPLICATION
- url: /.*
  script: main.application
- url: /update_schema
  script: update_schema_handler.app  # path to webapp2 application definition.
  login: admin

libraries:
- name: webapp2
  version: latest
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
- name: ssl
  version: latest
